return {
  {
    "bluz71/vim-moonfly-colors",
    name = "moonfly",
    lazy = false,
    priority = 1000,
  },
  { "Rigellute/rigel" },
  { "Shadorain/shadotheme" },
  { "catppuccin/nvim" },
  { "cocopon/iceberg.vim" },
  { "fenetikm/falcon" },
  { "folke/tokyonight.nvim" },
  { "jaredgorski/SpaceCamp" },
  { "joshdick/onedark.vim" },
  { "kyazdani42/blue-moon" },
  { "kyoz/purify" },
  { "neanias/everforest-nvim" },
  { "nlknguyen/papercolor-theme" },
  { "savq/melange-nvim" },
  { "tiagovla/tokyodark.nvim" },
  { "tomasr/molokai" },
  { "voidekh/kyotonight.vim" },
}
