[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.glyph_offset]
x = 0
y = -1

[font.normal]
family = "FiraCode"
style = "Medium"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control|Shift"

[general]
import = ["alacritty-theme/themes/iterm.toml"]
