(require 'semantic/bovine/gcc)

(add-hook 'c-mode-common-hook
          (lambda ()
            (semantic-mode 1)
            (setq-default backward-delete-function nil)
            (c-add-style "my-c-style"
                         '((c-basic-offset . 4)
                           (c-offsets-alist (label . +))))
            (c-set-style "my-c-style")
            (c-set-offset 'substatement-open '0)
            (c-set-offset 'inline-open '0)
            ;; (c-set-offset 'block-open '+)
            ;; (c-set-offset 'brace-list-open '+)
            ;; (c-set-offset 'case-label '+)
            (setq tab-width 4)
            (setq align-to-tab-stop nil)
            (c-set-offset 'substatement-open 0)
            ;; (company-mode)
            ;; (local-set-key (kbd "<tab>") 'company-complete-common)
            (rainbow-delimiters-mode 1)
            (define-key evil-normal-state-map (kbd "M-.") nil)
            (global-set-key "\M-." 'ggtags-find-tag-dwim)
            (local-set-key  (kbd "C-x o") 'ff-find-other-file)
            (local-set-key  (kbd "C-x C-o") 'ff-find-other-file)
            (when (derived-mode-p 'c-mode 'c++-mode 'java-mode 'asm-mode)
              (ggtags-mode 1)
              (define-key ggtags-mode-map (kbd "C-c t s") 'ggtags-find-other-symbol)
              (define-key ggtags-mode-map (kbd "C-c t h") 'ggtags-view-tag-history)
              (define-key ggtags-mode-map (kbd "C-c t r") 'ggtags-find-reference)
              (define-key ggtags-mode-map (kbd "C-c t c") 'ggtags-create-tags)
              (define-key ggtags-mode-map (kbd "C-c t u") 'ggtags-update-tags)

              (define-key ggtags-mode-map (kbd "M-,") 'pop-tag-mark))

            (add-to-list 'semantic-default-submodes 'global-semanticdb-minor-mode)
            (add-to-list 'semantic-default-submodes 'global-semantic-idle-scheduler-mode)
            (add-to-list 'semantic-default-submodes 'global-semantic-idle-summary-mode)
            (global-ede-mode t)
            (ede-enable-generic-projects)
            (evil-leader/set-key "a" 'ff-find-other-file)))

(provide 'init-c-common)
