# Local Variables:
# mode: makefile
# indent-tabs-mode: nil
# End:
# vim: set ft=make :

build:
    #!/usr/bin/env bash
    src_dir=~/code/xmonad-jco
    cd $src_dir
    nix-shell --run \
        'cabal configure --enable-optimization --enable-executable-stripping && \
        cabal build'
