name: xmonad-jco
version: 0.1.0
synopsis: XMonad configuration
github: joncol/dotfiles
author: Jonas Collberg
maintainer: jonas.collberg@gmail.com
copyright: © Jonas Collberg
license: MIT
dependencies:
  - X11
  - base
  - containers
  - data-default
  - utf8-string
  - xmonad
  - xmonad-contrib
executables:
  xmonad:
    main: xmonad.hs
    ghc-options:
      - -Wall
      - -fwarn-tabs
      - -threaded
      - -O2
      - -with-rtsopts=-N4
